server:
  port: 8003
spring:
  application:
    name: microservice-eureka-server
  freemarker:
# resove eureka welcome page is xml but not UI 
    prefer-file-system-access: false
eureka:
  instance:
    hostname: localhsot
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
#      tomcat start config:
#      defaultZone: http://${eureka.instance.hostname}:{server.port}/microservice-eureka-server/eureka
       defaultZone: http://${eureka.instance.hostname}:{server.port}/eureka