server:
  port: 8005
spring:
  application:
    name: microservice-eureka-server
  jmx:   
     default-domain: microservice-eureka-server
  freemarker:
# resove eureka welcome page is xml but not UI 
    prefer-file-system-access: false
#  启用不同配置文件：
#   cluster: 为了满足同一Application的不同Instance,提供HelloController接口
#   standalone: eureka不注册自己,适用于单一的eureka环境
  profiles:
    active:
    - standalone

