server:
  port: 8001
spring:
  freemarker:
# resove eureka welcome page is xml but not UI 
    prefer-file-system-access: false
eureka:
  server: 
    enableSelfPreservation: false 
  instance:
    hostname: peer1
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
       defaultZone: http://peer2:8002/eureka/