server:
  port: 8003
eureka:
  instance:
    hostname: localhsot
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/